//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Portfolio
{
	protected Dictionary<string, Position> positions;

	public virtual double Value
	{
        get
        {
            double returnVal = 0;
            foreach (Position p in this.positions.Values)
                returnVal += p.value;
            return returnVal;
        }
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Purchase(string symbol, Purchase purchase)
	{
        if (!this.positions.Keys.Contains(symbol))
            this.positions.Add(symbol, new Position(purchase));
        else
            this.positions[symbol].Purchase(purchase);
	}

	public virtual void Sell(string symbol, Sale sale)
	{
        this.positions[symbol].Sell(sale);
	}

	public virtual double GainLossReport(DateTime startDate, DateTime endDate)
	{
        double returnVal = 0;
        foreach (Position p in this.positions.Values)
            returnVal += p.GainLossReport(startDate, endDate);
        return returnVal;
	}

	public Portfolio()
	{
        this.positions = new Dictionary<string, Position>();
	}

}

