//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Position
{
	protected virtual List<Trade> purchases
	{
		get;
		set;
	}

	protected virtual List<Trade> sales
	{
		get;
		set;
	}

	public virtual double value
	{
		get;
		private set;
	}

	public virtual IEnumerable<Trade> Trade
	{
		get;
		set;
	}

	public virtual IEnumerable<Trade> Trade
	{
		get;
		set;
	}

	public virtual double GainLossReport(DateTime startDate, DateTime endDate)
	{
		throw new System.NotImplementedException();
	}

	public Position(double currPrice, int initalShares, DateTime purchaseDate)
	{
	}

	public virtual bool Purchase(Trade purchase)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool Sell(Trade purchase)
	{
		throw new System.NotImplementedException();
	}

}

