//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Simulator
{
	protected virtual User user1
	{
		get;
		set;
	}

	protected virtual Dictionary<string,Stock> stocks
	{
		get;
		set;
	}

	public virtual User User
	{
		get;
		set;
	}

	public virtual Stock Stock
	{
		get;
		set;
	}

	public Simulator()
	{
	}

}

