//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Stock
{
	public virtual double price
	{
		get;
		private set;
	}

	public virtual string name
	{
		get;
		private set;
	}

	public virtual void Stock(initName:string, initPrice:double()
	{
		throw new System.NotImplementedException();
	}

}

