//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Trade
{
	public virtual int numShares
	{
		get;
		private set;
	}

	public virtual double shareValue
	{
		get;
		private set;
	}

	public virtual double value
	{
		get;
		private set;
	}

	public virtual DateTime tradeDate
	{
		get;
		private set;
	}

	public Trade(int newNumShares, double newShareValue, DateTime newTradeDate)
	{
	}

}

