//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	protected virtual Dictionary<string, Portfolio> portfolios
	{
		get;
		set;
	}

	protected virtual int numPorts
	{
		get;
		set;
	}

	protected virtual double balance
	{
		get;
		set;
	}

	public virtual double tradeFee
	{
		get;
		private set;
	}

	public virtual double transferFee
	{
		get;
		private set;
	}

	public virtual IEnumerable<Portfolio> Portfolio
	{
		get;
		set;
	}

	public virtual double AccountBalance()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddFunds(double addAmount)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool WithdrawFunds(double withAmount)
	{
		throw new System.NotImplementedException();
	}

	public User(double newTradeFee, double newTransferFee, double initBalance)
	{
	}

	public virtual bool AddPortfolio(string portName)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool Purchase(string port, string symbol, int numShares, double shareValue, DateTime tradeDate)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool Sell(string port, string symbol, int numShares, double shareValue, DateTime tradeDate)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool DeletePortfolio(string portName)
	{
		throw new System.NotImplementedException();
	}

	public virtual double GainLossReport(string portName, DateTime startDate, DateTime endDate)
	{
		throw new System.NotImplementedException();
	}

}

